sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t vaib1343/docker-react -f Dockerfile.dev .


script: 
  - docker run -e CI=true vaib1343/docker-react npm run test